#Allure Environment Properties
#Wed Jul 23 12:10:55 IST 2025
Java.Version=17.0.15
OS=Linux
Test\ URL=https\://app2.dazhboards.com/
Browser.Version=124
Environment=Staging
Quality\ Engineer=Pankaj
Browser=Chrome
